project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    left:
      - text: "Overview"
        file: index.ipynb
    right:
      - icon: github
        href: https://github.com/pymjer/learn-data-analysis
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]