# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/learn-data-analysis',
                'doc_host': 'https://pymjer.github.io',
                'git_url': 'https://github.com/pymjer/learn-data-analysis',
                'lib_path': 'learn_data_analysis'},
  'syms': {'learn_data_analysis.core': {'learn_data_analysis.core.foo': ('core.html#foo', 'learn_data_analysis/core.py')}}}
